# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Zyht42-qTOIQgEjF80_VEVuhQZkrOh_
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
def min4(a,b,c,d):
  return min(min(min(a, b), c), d)
print(min4(a, b, c, d))

n = int(input())
def my_div(n):
  max=n
  for i in range(2,n//2+1):
    if n%i==0:
      max=i
  return max
print("наибольший делитель: " + str(my_div(n)))

a = int(input())
b = int(input())
def sum(a, b):
    if a == 0:
        return b;
    return sum(a-1, b+1)
print(sum(a,b))

a = int(input())
n = int(input())
def power(a,n):
  if n==0:
    return 1
  else:
    return a*power(a,n-1)
print(power(a,n))

xx = ['Makar Sidorov 26','Maria Kuznetsova 20','Peter Petrov 21','Ivan Ivanov 23']
p=sorted(xx, key=lambda x: str(x[-2:]))
print(p[0])